// SC2 unit & building data — Legacy of the Void (current balance reference values).
// All build times are GAME SECONDS. Real-time on default "Faster" speed = game / 1.4.
// Edit values here freely — the calculator will pick them up on reload.
//
// Each entity has:
//   id, name, race, type:                identity
//   buildTime (s), minerals, gas:        cost
//   supply:                              for units, supply cost (positive) or -provides (Overlord/Pylon/Depot etc. listed in `provides`)
//   prerequisites: [id, ...]             everything that must EXIST before this can START
//   producedBy: id                       (display) what trains/morphs this unit
//   builtBy: id                          (display) what worker constructs this building
//   upgradeFrom: id                      (display) source structure for upgrades (Lair, Orbital, etc.)
//   starting: true                       we own one at game start (eft = 0)
//   note: string                         shown to the user

const SC2_DATA = {
  patch: "Legacy of the Void — current balance",
  speedMultiplier: 1.4, // Faster (default ladder) speed
  notes: [
    "All build times are in GAME seconds (the value SC2 internally tracks).",
    "Default ladder speed is 'Faster', which runs game time at 1.4× real-time.",
    "Earliest timings assume infinite resources and that every prerequisite is started the instant it becomes possible.",
    "Pylon power, Creep, and worker travel time are NOT modeled. In practice these add a few seconds.",
    "For Protoss, Warp Gate research is not used — Gateway training times are shown.",
    "For Zerg, larva availability is assumed to never bottleneck.",
  ],

  entities: {
    // ============================================================
    // TERRAN
    // ============================================================
    scv: {
      id: "scv", name: "SCV", race: "terran", type: "unit", role: "worker",
      buildTime: 12, minerals: 50, gas: 0, supply: 1,
      prerequisites: ["command_center"], producedBy: "command_center", starting: true,
    },
    command_center: {
      id: "command_center", name: "Command Center", race: "terran", type: "building",
      buildTime: 71, minerals: 400, gas: 0, provides: 15,
      prerequisites: [], builtBy: "scv", starting: true,
    },
    orbital_command: {
      id: "orbital_command", name: "Orbital Command", race: "terran", type: "building",
      note: "Upgrade from Command Center",
      buildTime: 25, minerals: 150, gas: 0,
      prerequisites: ["command_center", "barracks"], upgradeFrom: "command_center",
    },
    planetary_fortress: {
      id: "planetary_fortress", name: "Planetary Fortress", race: "terran", type: "building",
      note: "Upgrade from Command Center",
      buildTime: 36, minerals: 150, gas: 150,
      prerequisites: ["command_center", "engineering_bay"], upgradeFrom: "command_center",
    },
    supply_depot: {
      id: "supply_depot", name: "Supply Depot", race: "terran", type: "building",
      buildTime: 21, minerals: 100, gas: 0, provides: 8,
      prerequisites: [], builtBy: "scv",
    },
    refinery: {
      id: "refinery", name: "Refinery", race: "terran", type: "building",
      buildTime: 21, minerals: 75, gas: 0,
      prerequisites: [], builtBy: "scv",
    },
    barracks: {
      id: "barracks", name: "Barracks", race: "terran", type: "building",
      buildTime: 46, minerals: 150, gas: 0,
      prerequisites: ["supply_depot"], builtBy: "scv",
    },
    engineering_bay: {
      id: "engineering_bay", name: "Engineering Bay", race: "terran", type: "building",
      buildTime: 25, minerals: 125, gas: 0,
      prerequisites: ["command_center"], builtBy: "scv",
    },
    bunker: {
      id: "bunker", name: "Bunker", race: "terran", type: "building",
      buildTime: 29, minerals: 100, gas: 0,
      prerequisites: ["barracks"], builtBy: "scv",
    },
    missile_turret: {
      id: "missile_turret", name: "Missile Turret", race: "terran", type: "building",
      buildTime: 18, minerals: 100, gas: 0,
      prerequisites: ["engineering_bay"], builtBy: "scv",
    },
    sensor_tower: {
      id: "sensor_tower", name: "Sensor Tower", race: "terran", type: "building",
      buildTime: 18, minerals: 100, gas: 50,
      prerequisites: ["engineering_bay"], builtBy: "scv",
    },
    factory: {
      id: "factory", name: "Factory", race: "terran", type: "building",
      buildTime: 43, minerals: 150, gas: 100,
      prerequisites: ["barracks"], builtBy: "scv",
    },
    ghost_academy: {
      id: "ghost_academy", name: "Ghost Academy", race: "terran", type: "building",
      buildTime: 29, minerals: 150, gas: 50,
      prerequisites: ["factory"], builtBy: "scv",
    },
    starport: {
      id: "starport", name: "Starport", race: "terran", type: "building",
      buildTime: 36, minerals: 150, gas: 100,
      prerequisites: ["factory"], builtBy: "scv",
    },
    armory: {
      id: "armory", name: "Armory", race: "terran", type: "building",
      buildTime: 46, minerals: 150, gas: 50,
      prerequisites: ["factory"], builtBy: "scv",
    },
    fusion_core: {
      id: "fusion_core", name: "Fusion Core", race: "terran", type: "building",
      buildTime: 46, minerals: 150, gas: 150,
      prerequisites: ["starport"], builtBy: "scv",
    },

    // Add-ons (built ON the parent structure; parent is busy during construction).
    barracks_techlab: {
      id: "barracks_techlab", name: "Barracks Tech Lab", race: "terran", type: "addon",
      buildTime: 18, minerals: 50, gas: 25,
      prerequisites: ["barracks"], producedBy: "barracks",
    },
    barracks_reactor: {
      id: "barracks_reactor", name: "Barracks Reactor", race: "terran", type: "addon",
      buildTime: 36, minerals: 50, gas: 50,
      prerequisites: ["barracks"], producedBy: "barracks",
    },
    factory_techlab: {
      id: "factory_techlab", name: "Factory Tech Lab", race: "terran", type: "addon",
      buildTime: 18, minerals: 50, gas: 25,
      prerequisites: ["factory"], producedBy: "factory",
    },
    factory_reactor: {
      id: "factory_reactor", name: "Factory Reactor", race: "terran", type: "addon",
      buildTime: 36, minerals: 50, gas: 50,
      prerequisites: ["factory"], producedBy: "factory",
    },
    starport_techlab: {
      id: "starport_techlab", name: "Starport Tech Lab", race: "terran", type: "addon",
      buildTime: 18, minerals: 50, gas: 25,
      prerequisites: ["starport"], producedBy: "starport",
    },
    starport_reactor: {
      id: "starport_reactor", name: "Starport Reactor", race: "terran", type: "addon",
      buildTime: 36, minerals: 50, gas: 50,
      prerequisites: ["starport"], producedBy: "starport",
    },

    // Terran units
    marine: {
      id: "marine", name: "Marine", race: "terran", type: "unit",
      buildTime: 18, minerals: 50, gas: 0, supply: 1,
      prerequisites: ["barracks"], producedBy: "barracks",
    },
    marauder: {
      id: "marauder", name: "Marauder", race: "terran", type: "unit",
      buildTime: 21, minerals: 100, gas: 25, supply: 2,
      prerequisites: ["barracks_techlab"], producedBy: "barracks",
    },
    reaper: {
      id: "reaper", name: "Reaper", race: "terran", type: "unit",
      buildTime: 32, minerals: 50, gas: 50, supply: 1,
      prerequisites: ["barracks"], producedBy: "barracks",
    },
    ghost: {
      id: "ghost", name: "Ghost", race: "terran", type: "unit",
      buildTime: 29, minerals: 150, gas: 125, supply: 2,
      prerequisites: ["barracks_techlab", "ghost_academy"], producedBy: "barracks",
    },
    hellion: {
      id: "hellion", name: "Hellion", race: "terran", type: "unit",
      buildTime: 21, minerals: 100, gas: 0, supply: 2,
      prerequisites: ["factory"], producedBy: "factory",
    },
    hellbat: {
      id: "hellbat", name: "Hellbat", race: "terran", type: "unit",
      note: "Requires Armory; transformed Hellion or built from Factory",
      buildTime: 21, minerals: 100, gas: 0, supply: 2,
      prerequisites: ["factory", "armory"], producedBy: "factory",
    },
    widow_mine: {
      id: "widow_mine", name: "Widow Mine", race: "terran", type: "unit",
      buildTime: 21, minerals: 75, gas: 25, supply: 2,
      prerequisites: ["factory"], producedBy: "factory",
    },
    cyclone: {
      id: "cyclone", name: "Cyclone", race: "terran", type: "unit",
      buildTime: 32, minerals: 150, gas: 100, supply: 3,
      prerequisites: ["factory_techlab"], producedBy: "factory",
    },
    siege_tank: {
      id: "siege_tank", name: "Siege Tank", race: "terran", type: "unit",
      buildTime: 32, minerals: 150, gas: 125, supply: 3,
      prerequisites: ["factory_techlab"], producedBy: "factory",
    },
    thor: {
      id: "thor", name: "Thor", race: "terran", type: "unit",
      buildTime: 43, minerals: 300, gas: 200, supply: 6,
      prerequisites: ["factory_techlab", "armory"], producedBy: "factory",
    },
    viking: {
      id: "viking", name: "Viking", race: "terran", type: "unit",
      buildTime: 30, minerals: 150, gas: 75, supply: 2,
      prerequisites: ["starport"], producedBy: "starport",
    },
    medivac: {
      id: "medivac", name: "Medivac", race: "terran", type: "unit",
      buildTime: 30, minerals: 100, gas: 100, supply: 2,
      prerequisites: ["starport"], producedBy: "starport",
    },
    liberator: {
      id: "liberator", name: "Liberator", race: "terran", type: "unit",
      buildTime: 43, minerals: 150, gas: 150, supply: 3,
      prerequisites: ["starport"], producedBy: "starport",
    },
    banshee: {
      id: "banshee", name: "Banshee", race: "terran", type: "unit",
      buildTime: 43, minerals: 150, gas: 100, supply: 3,
      prerequisites: ["starport_techlab"], producedBy: "starport",
    },
    raven: {
      id: "raven", name: "Raven", race: "terran", type: "unit",
      buildTime: 34, minerals: 100, gas: 150, supply: 2,
      prerequisites: ["starport_techlab"], producedBy: "starport",
    },
    battlecruiser: {
      id: "battlecruiser", name: "Battlecruiser", race: "terran", type: "unit",
      buildTime: 64, minerals: 400, gas: 300, supply: 6,
      prerequisites: ["starport_techlab", "fusion_core"], producedBy: "starport",
    },

    // ============================================================
    // PROTOSS
    // ============================================================
    probe: {
      id: "probe", name: "Probe", race: "protoss", type: "unit", role: "worker",
      buildTime: 12, minerals: 50, gas: 0, supply: 1,
      prerequisites: ["nexus"], producedBy: "nexus", starting: true,
    },
    nexus: {
      id: "nexus", name: "Nexus", race: "protoss", type: "building",
      buildTime: 71, minerals: 400, gas: 0, provides: 15,
      prerequisites: [], builtBy: "probe", starting: true,
    },
    pylon: {
      id: "pylon", name: "Pylon", race: "protoss", type: "building",
      buildTime: 18, minerals: 100, gas: 0, provides: 8,
      prerequisites: [], builtBy: "probe",
    },
    assimilator: {
      id: "assimilator", name: "Assimilator", race: "protoss", type: "building",
      buildTime: 21, minerals: 75, gas: 0,
      prerequisites: [], builtBy: "probe",
    },
    gateway: {
      id: "gateway", name: "Gateway", race: "protoss", type: "building",
      buildTime: 46, minerals: 150, gas: 0,
      prerequisites: ["nexus", "pylon"], builtBy: "probe",
      note: "Requires Pylon for power",
    },
    forge: {
      id: "forge", name: "Forge", race: "protoss", type: "building",
      buildTime: 32, minerals: 150, gas: 0,
      prerequisites: ["nexus", "pylon"], builtBy: "probe",
      note: "Requires Pylon for power",
    },
    cybernetics_core: {
      id: "cybernetics_core", name: "Cybernetics Core", race: "protoss", type: "building",
      buildTime: 36, minerals: 150, gas: 0,
      prerequisites: ["gateway"], builtBy: "probe",
    },
    photon_cannon: {
      id: "photon_cannon", name: "Photon Cannon", race: "protoss", type: "building",
      buildTime: 29, minerals: 150, gas: 0,
      prerequisites: ["forge"], builtBy: "probe",
    },
    shield_battery: {
      id: "shield_battery", name: "Shield Battery", race: "protoss", type: "building",
      buildTime: 29, minerals: 100, gas: 0,
      prerequisites: ["cybernetics_core"], builtBy: "probe",
    },
    twilight_council: {
      id: "twilight_council", name: "Twilight Council", race: "protoss", type: "building",
      buildTime: 36, minerals: 150, gas: 100,
      prerequisites: ["cybernetics_core"], builtBy: "probe",
    },
    stargate: {
      id: "stargate", name: "Stargate", race: "protoss", type: "building",
      buildTime: 43, minerals: 150, gas: 150,
      prerequisites: ["cybernetics_core"], builtBy: "probe",
    },
    robotics_facility: {
      id: "robotics_facility", name: "Robotics Facility", race: "protoss", type: "building",
      buildTime: 46, minerals: 150, gas: 100,
      prerequisites: ["cybernetics_core"], builtBy: "probe",
    },
    robotics_bay: {
      id: "robotics_bay", name: "Robotics Bay", race: "protoss", type: "building",
      buildTime: 46, minerals: 150, gas: 150,
      prerequisites: ["robotics_facility"], builtBy: "probe",
    },
    templar_archives: {
      id: "templar_archives", name: "Templar Archives", race: "protoss", type: "building",
      buildTime: 36, minerals: 150, gas: 200,
      prerequisites: ["twilight_council"], builtBy: "probe",
    },
    dark_shrine: {
      id: "dark_shrine", name: "Dark Shrine", race: "protoss", type: "building",
      buildTime: 71, minerals: 150, gas: 150,
      prerequisites: ["twilight_council"], builtBy: "probe",
    },
    fleet_beacon: {
      id: "fleet_beacon", name: "Fleet Beacon", race: "protoss", type: "building",
      buildTime: 43, minerals: 300, gas: 200,
      prerequisites: ["stargate"], builtBy: "probe",
    },

    // Protoss units
    zealot: {
      id: "zealot", name: "Zealot", race: "protoss", type: "unit",
      buildTime: 27, minerals: 100, gas: 0, supply: 2,
      prerequisites: ["gateway"], producedBy: "gateway",
    },
    stalker: {
      id: "stalker", name: "Stalker", race: "protoss", type: "unit",
      buildTime: 27, minerals: 125, gas: 50, supply: 2,
      prerequisites: ["cybernetics_core"], producedBy: "gateway",
    },
    sentry: {
      id: "sentry", name: "Sentry", race: "protoss", type: "unit",
      buildTime: 23, minerals: 50, gas: 100, supply: 2,
      prerequisites: ["cybernetics_core"], producedBy: "gateway",
    },
    adept: {
      id: "adept", name: "Adept", race: "protoss", type: "unit",
      buildTime: 30, minerals: 100, gas: 25, supply: 2,
      prerequisites: ["cybernetics_core"], producedBy: "gateway",
    },
    high_templar: {
      id: "high_templar", name: "High Templar", race: "protoss", type: "unit",
      buildTime: 39, minerals: 50, gas: 150, supply: 2,
      prerequisites: ["templar_archives"], producedBy: "gateway",
    },
    dark_templar: {
      id: "dark_templar", name: "Dark Templar", race: "protoss", type: "unit",
      buildTime: 39, minerals: 125, gas: 125, supply: 2,
      prerequisites: ["dark_shrine"], producedBy: "gateway",
    },
    archon: {
      id: "archon", name: "Archon", race: "protoss", type: "unit",
      note: "Morphed from 2 High/Dark Templar (cost is 0 — pays in templar)",
      buildTime: 9, minerals: 0, gas: 0, supply: 4,
      prerequisites: ["high_templar"], producedBy: "high_templar",
    },
    immortal: {
      id: "immortal", name: "Immortal", race: "protoss", type: "unit",
      buildTime: 39, minerals: 250, gas: 100, supply: 4,
      prerequisites: ["robotics_facility"], producedBy: "robotics_facility",
    },
    colossus: {
      id: "colossus", name: "Colossus", race: "protoss", type: "unit",
      buildTime: 54, minerals: 300, gas: 200, supply: 6,
      prerequisites: ["robotics_bay"], producedBy: "robotics_facility",
    },
    disruptor: {
      id: "disruptor", name: "Disruptor", race: "protoss", type: "unit",
      buildTime: 36, minerals: 150, gas: 150, supply: 4,
      prerequisites: ["robotics_bay"], producedBy: "robotics_facility",
    },
    observer: {
      id: "observer", name: "Observer", race: "protoss", type: "unit",
      buildTime: 18, minerals: 25, gas: 75, supply: 1,
      prerequisites: ["robotics_facility"], producedBy: "robotics_facility",
    },
    warp_prism: {
      id: "warp_prism", name: "Warp Prism", race: "protoss", type: "unit",
      buildTime: 36, minerals: 250, gas: 0, supply: 2,
      prerequisites: ["robotics_facility"], producedBy: "robotics_facility",
    },
    phoenix: {
      id: "phoenix", name: "Phoenix", race: "protoss", type: "unit",
      buildTime: 25, minerals: 150, gas: 100, supply: 2,
      prerequisites: ["stargate"], producedBy: "stargate",
    },
    void_ray: {
      id: "void_ray", name: "Void Ray", race: "protoss", type: "unit",
      buildTime: 43, minerals: 250, gas: 150, supply: 4,
      prerequisites: ["stargate"], producedBy: "stargate",
    },
    oracle: {
      id: "oracle", name: "Oracle", race: "protoss", type: "unit",
      buildTime: 37, minerals: 150, gas: 150, supply: 3,
      prerequisites: ["stargate"], producedBy: "stargate",
    },
    tempest: {
      id: "tempest", name: "Tempest", race: "protoss", type: "unit",
      buildTime: 43, minerals: 250, gas: 175, supply: 4,
      prerequisites: ["fleet_beacon"], producedBy: "stargate",
    },
    carrier: {
      id: "carrier", name: "Carrier", race: "protoss", type: "unit",
      buildTime: 64, minerals: 350, gas: 250, supply: 6,
      prerequisites: ["fleet_beacon"], producedBy: "stargate",
    },
    mothership: {
      id: "mothership", name: "Mothership", race: "protoss", type: "unit",
      buildTime: 89, minerals: 400, gas: 400, supply: 8,
      prerequisites: ["fleet_beacon"], producedBy: "nexus",
    },

    // ============================================================
    // ZERG
    // ============================================================
    drone: {
      id: "drone", name: "Drone", race: "zerg", type: "unit", role: "worker",
      buildTime: 12, minerals: 50, gas: 0, supply: 1,
      prerequisites: ["hatchery"], producedBy: "hatchery", starting: true,
    },
    larva: {
      id: "larva", name: "Larva", race: "zerg", type: "unit",
      note: "Spawns at Hatchery automatically",
      buildTime: 0, minerals: 0, gas: 0, supply: 0,
      prerequisites: ["hatchery"], producedBy: "hatchery", starting: true,
    },
    overlord: {
      id: "overlord", name: "Overlord", race: "zerg", type: "unit",
      buildTime: 18, minerals: 100, gas: 0, supply: 0, provides: 8,
      prerequisites: ["hatchery"], producedBy: "hatchery", starting: true,
    },
    hatchery: {
      id: "hatchery", name: "Hatchery", race: "zerg", type: "building",
      buildTime: 71, minerals: 275, gas: 0, provides: 6,
      prerequisites: [], builtBy: "drone", starting: true,
    },
    lair: {
      id: "lair", name: "Lair", race: "zerg", type: "building",
      note: "Upgrade from Hatchery",
      buildTime: 57, minerals: 150, gas: 100,
      prerequisites: ["hatchery", "spawning_pool"], upgradeFrom: "hatchery",
    },
    hive: {
      id: "hive", name: "Hive", race: "zerg", type: "building",
      note: "Upgrade from Lair",
      buildTime: 71, minerals: 200, gas: 150,
      prerequisites: ["lair", "infestation_pit"], upgradeFrom: "lair",
    },
    extractor: {
      id: "extractor", name: "Extractor", race: "zerg", type: "building",
      buildTime: 21, minerals: 25, gas: 0,
      prerequisites: [], builtBy: "drone",
    },
    spawning_pool: {
      id: "spawning_pool", name: "Spawning Pool", race: "zerg", type: "building",
      buildTime: 46, minerals: 200, gas: 0,
      prerequisites: ["hatchery"], builtBy: "drone",
    },
    evolution_chamber: {
      id: "evolution_chamber", name: "Evolution Chamber", race: "zerg", type: "building",
      buildTime: 25, minerals: 75, gas: 0,
      prerequisites: ["hatchery"], builtBy: "drone",
    },
    roach_warren: {
      id: "roach_warren", name: "Roach Warren", race: "zerg", type: "building",
      buildTime: 39, minerals: 150, gas: 0,
      prerequisites: ["spawning_pool"], builtBy: "drone",
    },
    baneling_nest: {
      id: "baneling_nest", name: "Baneling Nest", race: "zerg", type: "building",
      buildTime: 43, minerals: 100, gas: 50,
      prerequisites: ["spawning_pool"], builtBy: "drone",
    },
    spine_crawler: {
      id: "spine_crawler", name: "Spine Crawler", race: "zerg", type: "building",
      buildTime: 36, minerals: 100, gas: 0,
      prerequisites: ["spawning_pool"], builtBy: "drone",
    },
    spore_crawler: {
      id: "spore_crawler", name: "Spore Crawler", race: "zerg", type: "building",
      buildTime: 21, minerals: 75, gas: 0,
      prerequisites: ["spawning_pool"], builtBy: "drone",
    },
    hydralisk_den: {
      id: "hydralisk_den", name: "Hydralisk Den", race: "zerg", type: "building",
      buildTime: 29, minerals: 100, gas: 100,
      prerequisites: ["lair"], builtBy: "drone",
    },
    lurker_den: {
      id: "lurker_den", name: "Lurker Den", race: "zerg", type: "building",
      buildTime: 57, minerals: 150, gas: 150,
      prerequisites: ["hydralisk_den"], builtBy: "drone",
    },
    infestation_pit: {
      id: "infestation_pit", name: "Infestation Pit", race: "zerg", type: "building",
      buildTime: 36, minerals: 100, gas: 100,
      prerequisites: ["lair"], builtBy: "drone",
    },
    spire: {
      id: "spire", name: "Spire", race: "zerg", type: "building",
      buildTime: 66, minerals: 150, gas: 150,
      prerequisites: ["lair"], builtBy: "drone",
    },
    greater_spire: {
      id: "greater_spire", name: "Greater Spire", race: "zerg", type: "building",
      note: "Upgrade from Spire",
      buildTime: 71, minerals: 100, gas: 150,
      prerequisites: ["spire", "hive"], upgradeFrom: "spire",
    },
    nydus_network: {
      id: "nydus_network", name: "Nydus Network", race: "zerg", type: "building",
      buildTime: 36, minerals: 150, gas: 150,
      prerequisites: ["lair"], builtBy: "drone",
    },
    ultralisk_cavern: {
      id: "ultralisk_cavern", name: "Ultralisk Cavern", race: "zerg", type: "building",
      buildTime: 46, minerals: 150, gas: 200,
      prerequisites: ["hive"], builtBy: "drone",
    },

    // Zerg units
    queen: {
      id: "queen", name: "Queen", race: "zerg", type: "unit",
      note: "Trained at Hatchery (does not consume larva)",
      buildTime: 36, minerals: 175, gas: 0, supply: 2,
      prerequisites: ["hatchery", "spawning_pool"], producedBy: "hatchery",
    },
    zergling: {
      id: "zergling", name: "Zergling", race: "zerg", type: "unit",
      note: "1 larva yields 2 Zerglings (cost shown is per pair)",
      buildTime: 17, minerals: 50, gas: 0, supply: 1,
      prerequisites: ["spawning_pool"], producedBy: "hatchery",
    },
    baneling: {
      id: "baneling", name: "Baneling", race: "zerg", type: "unit",
      note: "Morphed from Zergling",
      buildTime: 14, minerals: 25, gas: 25, supply: 0,
      prerequisites: ["zergling", "baneling_nest"], producedBy: "zergling",
    },
    roach: {
      id: "roach", name: "Roach", race: "zerg", type: "unit",
      buildTime: 19, minerals: 75, gas: 25, supply: 2,
      prerequisites: ["roach_warren"], producedBy: "hatchery",
    },
    ravager: {
      id: "ravager", name: "Ravager", race: "zerg", type: "unit",
      note: "Morphed from Roach",
      buildTime: 9, minerals: 25, gas: 75, supply: 1,
      prerequisites: ["roach"], producedBy: "roach",
    },
    hydralisk: {
      id: "hydralisk", name: "Hydralisk", race: "zerg", type: "unit",
      buildTime: 24, minerals: 100, gas: 50, supply: 2,
      prerequisites: ["hydralisk_den"], producedBy: "hatchery",
    },
    lurker: {
      id: "lurker", name: "Lurker", race: "zerg", type: "unit",
      note: "Morphed from Hydralisk",
      buildTime: 18, minerals: 50, gas: 100, supply: 1,
      prerequisites: ["hydralisk", "lurker_den"], producedBy: "hydralisk",
    },
    mutalisk: {
      id: "mutalisk", name: "Mutalisk", race: "zerg", type: "unit",
      buildTime: 24, minerals: 100, gas: 100, supply: 2,
      prerequisites: ["spire"], producedBy: "hatchery",
    },
    corruptor: {
      id: "corruptor", name: "Corruptor", race: "zerg", type: "unit",
      buildTime: 29, minerals: 150, gas: 100, supply: 2,
      prerequisites: ["spire"], producedBy: "hatchery",
    },
    brood_lord: {
      id: "brood_lord", name: "Brood Lord", race: "zerg", type: "unit",
      note: "Morphed from Corruptor",
      buildTime: 24, minerals: 150, gas: 150, supply: 2,
      prerequisites: ["corruptor", "greater_spire"], producedBy: "corruptor",
    },
    overseer: {
      id: "overseer", name: "Overseer", race: "zerg", type: "unit",
      note: "Morphed from Overlord",
      buildTime: 12, minerals: 50, gas: 50, supply: 0,
      prerequisites: ["overlord", "lair"], producedBy: "overlord",
    },
    infestor: {
      id: "infestor", name: "Infestor", race: "zerg", type: "unit",
      buildTime: 36, minerals: 100, gas: 150, supply: 2,
      prerequisites: ["infestation_pit"], producedBy: "hatchery",
    },
    swarm_host: {
      id: "swarm_host", name: "Swarm Host", race: "zerg", type: "unit",
      buildTime: 29, minerals: 100, gas: 75, supply: 3,
      prerequisites: ["infestation_pit"], producedBy: "hatchery",
    },
    viper: {
      id: "viper", name: "Viper", race: "zerg", type: "unit",
      buildTime: 29, minerals: 100, gas: 200, supply: 3,
      prerequisites: ["hive"], producedBy: "hatchery",
    },
    ultralisk: {
      id: "ultralisk", name: "Ultralisk", race: "zerg", type: "unit",
      buildTime: 39, minerals: 300, gas: 200, supply: 6,
      prerequisites: ["ultralisk_cavern"], producedBy: "hatchery",
    },
    nydus_worm: {
      id: "nydus_worm", name: "Nydus Worm", race: "zerg", type: "unit",
      buildTime: 14, minerals: 75, gas: 75, supply: 0,
      prerequisites: ["nydus_network"], producedBy: "nydus_network",
    },

    // ============================================================
    // UPGRADES / RESEARCHES
    // ============================================================
    // Each upgrade has: race, type='upgrade', buildTime (research time, game seconds),
    //   minerals/gas, prerequisites (the research building, plus any others), producedBy
    //   (the structure that researches it; busy during research).

    // ---- Terran upgrades ----
    stimpack: { id: "stimpack", name: "Stimpack", race: "terran", type: "upgrade",
      buildTime: 100, minerals: 100, gas: 100,
      prerequisites: ["barracks_techlab"], producedBy: "barracks_techlab",
      note: "Marine/Marauder activated speed+attack boost" },
    combat_shield: { id: "combat_shield", name: "Combat Shield", race: "terran", type: "upgrade",
      buildTime: 79, minerals: 100, gas: 100,
      prerequisites: ["barracks_techlab"], producedBy: "barracks_techlab",
      note: "Marine +10 HP" },
    concussive_shells: { id: "concussive_shells", name: "Concussive Shells", race: "terran", type: "upgrade",
      buildTime: 43, minerals: 50, gas: 50,
      prerequisites: ["barracks_techlab"], producedBy: "barracks_techlab",
      note: "Marauder slowing attack" },
    personal_cloaking: { id: "personal_cloaking", name: "Personal Cloaking", race: "terran", type: "upgrade",
      buildTime: 86, minerals: 150, gas: 150,
      prerequisites: ["ghost_academy"], producedBy: "ghost_academy",
      note: "Ghost cloak" },
    drilling_claws: { id: "drilling_claws", name: "Drilling Claws", race: "terran", type: "upgrade",
      buildTime: 79, minerals: 75, gas: 75,
      prerequisites: ["factory_techlab", "armory"], producedBy: "factory_techlab",
      note: "Widow Mine faster burrow / unburrow" },
    smart_servos: { id: "smart_servos", name: "Smart Servos", race: "terran", type: "upgrade",
      buildTime: 79, minerals: 100, gas: 100,
      prerequisites: ["factory_techlab", "armory"], producedBy: "factory_techlab",
      note: "Hellion / Viking / Thor faster transformation" },
    cloaking_field: { id: "cloaking_field", name: "Cloaking Field", race: "terran", type: "upgrade",
      buildTime: 79, minerals: 100, gas: 100,
      prerequisites: ["starport_techlab"], producedBy: "starport_techlab",
      note: "Banshee cloak" },
    hyperflight_rotors: { id: "hyperflight_rotors", name: "Hyperflight Rotors", race: "terran", type: "upgrade",
      buildTime: 79, minerals: 125, gas: 125,
      prerequisites: ["starport_techlab"], producedBy: "starport_techlab",
      note: "Banshee speed" },
    interference_matrix: { id: "interference_matrix", name: "Interference Matrix", race: "terran", type: "upgrade",
      buildTime: 57, minerals: 50, gas: 50,
      prerequisites: ["starport_techlab"], producedBy: "starport_techlab",
      note: "Raven Interference Matrix" },
    caduceus_reactor: { id: "caduceus_reactor", name: "Caduceus Reactor", race: "terran", type: "upgrade",
      buildTime: 80, minerals: 100, gas: 100,
      prerequisites: ["starport_techlab"], producedBy: "starport_techlab",
      note: "Medivac +25 starting energy" },
    yamato_cannon: { id: "yamato_cannon", name: "Yamato Cannon", race: "terran", type: "upgrade",
      buildTime: 71, minerals: 150, gas: 150,
      prerequisites: ["fusion_core"], producedBy: "fusion_core",
      note: "Battlecruiser Yamato" },
    weapon_refit: { id: "weapon_refit", name: "Weapon Refit", race: "terran", type: "upgrade",
      buildTime: 100, minerals: 150, gas: 150,
      prerequisites: ["fusion_core"], producedBy: "fusion_core",
      note: "BC ground attack +1" },
    // Infantry upgrades (Engineering Bay)
    inf_weapons_1: { id: "inf_weapons_1", name: "Infantry Weapons +1", race: "terran", type: "upgrade",
      buildTime: 114, minerals: 100, gas: 100,
      prerequisites: ["engineering_bay"], producedBy: "engineering_bay" },
    inf_weapons_2: { id: "inf_weapons_2", name: "Infantry Weapons +2", race: "terran", type: "upgrade",
      buildTime: 136, minerals: 150, gas: 150,
      prerequisites: ["engineering_bay", "armory", "inf_weapons_1"], producedBy: "engineering_bay" },
    inf_weapons_3: { id: "inf_weapons_3", name: "Infantry Weapons +3", race: "terran", type: "upgrade",
      buildTime: 157, minerals: 200, gas: 200,
      prerequisites: ["engineering_bay", "armory", "inf_weapons_2"], producedBy: "engineering_bay" },
    inf_armor_1: { id: "inf_armor_1", name: "Infantry Armor +1", race: "terran", type: "upgrade",
      buildTime: 114, minerals: 100, gas: 100,
      prerequisites: ["engineering_bay"], producedBy: "engineering_bay" },
    inf_armor_2: { id: "inf_armor_2", name: "Infantry Armor +2", race: "terran", type: "upgrade",
      buildTime: 136, minerals: 150, gas: 150,
      prerequisites: ["engineering_bay", "armory", "inf_armor_1"], producedBy: "engineering_bay" },
    inf_armor_3: { id: "inf_armor_3", name: "Infantry Armor +3", race: "terran", type: "upgrade",
      buildTime: 157, minerals: 200, gas: 200,
      prerequisites: ["engineering_bay", "armory", "inf_armor_2"], producedBy: "engineering_bay" },

    // ---- Protoss upgrades ----
    warpgate_research: { id: "warpgate_research", name: "Warp Gate", race: "protoss", type: "upgrade",
      buildTime: 100, minerals: 50, gas: 50,
      prerequisites: ["cybernetics_core"], producedBy: "cybernetics_core",
      note: "Transforms Gateways into Warp Gates" },
    hallucination: { id: "hallucination", name: "Hallucination", race: "protoss", type: "upgrade",
      buildTime: 57, minerals: 100, gas: 100,
      prerequisites: ["cybernetics_core"], producedBy: "cybernetics_core",
      note: "Sentry hallucination" },
    charge: { id: "charge", name: "Charge", race: "protoss", type: "upgrade",
      buildTime: 100, minerals: 100, gas: 100,
      prerequisites: ["twilight_council"], producedBy: "twilight_council",
      note: "Zealot charge ability + speed" },
    blink: { id: "blink", name: "Blink", race: "protoss", type: "upgrade",
      buildTime: 121, minerals: 150, gas: 150,
      prerequisites: ["twilight_council"], producedBy: "twilight_council",
      note: "Stalker short-range teleport" },
    resonating_glaives: { id: "resonating_glaives", name: "Resonating Glaives", race: "protoss", type: "upgrade",
      buildTime: 100, minerals: 100, gas: 100,
      prerequisites: ["twilight_council"], producedBy: "twilight_council",
      note: "Adept attack speed" },
    psionic_storm: { id: "psionic_storm", name: "Psionic Storm", race: "protoss", type: "upgrade",
      buildTime: 79, minerals: 100, gas: 100,
      prerequisites: ["templar_archives"], producedBy: "templar_archives",
      note: "High Templar Storm" },
    shadow_stride: { id: "shadow_stride", name: "Shadow Stride", race: "protoss", type: "upgrade",
      buildTime: 121, minerals: 100, gas: 100,
      prerequisites: ["dark_shrine"], producedBy: "dark_shrine",
      note: "Dark Templar blink" },
    extended_thermal_lance: { id: "extended_thermal_lance", name: "Extended Thermal Lance", race: "protoss", type: "upgrade",
      buildTime: 100, minerals: 150, gas: 150,
      prerequisites: ["robotics_bay"], producedBy: "robotics_bay",
      note: "Colossus range" },
    gravitic_drive: { id: "gravitic_drive", name: "Gravitic Drive", race: "protoss", type: "upgrade",
      buildTime: 57, minerals: 100, gas: 100,
      prerequisites: ["robotics_bay"], producedBy: "robotics_bay",
      note: "Warp Prism speed" },
    gravitic_boosters: { id: "gravitic_boosters", name: "Gravitic Boosters", race: "protoss", type: "upgrade",
      buildTime: 57, minerals: 100, gas: 100,
      prerequisites: ["robotics_bay"], producedBy: "robotics_bay",
      note: "Observer speed" },
    anion_pulse_crystals: { id: "anion_pulse_crystals", name: "Anion Pulse-Crystals", race: "protoss", type: "upgrade",
      buildTime: 64, minerals: 150, gas: 150,
      prerequisites: ["fleet_beacon"], producedBy: "fleet_beacon",
      note: "Phoenix range" },
    tectonic_destabilizers: { id: "tectonic_destabilizers", name: "Tectonic Destabilizers", race: "protoss", type: "upgrade",
      buildTime: 100, minerals: 150, gas: 150,
      prerequisites: ["fleet_beacon"], producedBy: "fleet_beacon",
      note: "Tempest +40 vs structures" },
    flux_vanes: { id: "flux_vanes", name: "Flux Vanes", race: "protoss", type: "upgrade",
      buildTime: 57, minerals: 100, gas: 100,
      prerequisites: ["fleet_beacon"], producedBy: "fleet_beacon",
      note: "Void Ray speed" },
    graviton_catapult: { id: "graviton_catapult", name: "Graviton Catapult", race: "protoss", type: "upgrade",
      buildTime: 57, minerals: 150, gas: 150,
      prerequisites: ["fleet_beacon"], producedBy: "fleet_beacon",
      note: "Carrier interceptor launch speed" },
    p_air_weapons_1: { id: "p_air_weapons_1", name: "Air Weapons +1", race: "protoss", type: "upgrade",
      buildTime: 129, minerals: 100, gas: 100,
      prerequisites: ["cybernetics_core"], producedBy: "cybernetics_core" },
    p_air_armor_1: { id: "p_air_armor_1", name: "Air Armor +1", race: "protoss", type: "upgrade",
      buildTime: 129, minerals: 100, gas: 100,
      prerequisites: ["cybernetics_core"], producedBy: "cybernetics_core" },
    // Ground upgrades (Forge)
    p_ground_weapons_1: { id: "p_ground_weapons_1", name: "Ground Weapons +1", race: "protoss", type: "upgrade",
      buildTime: 128, minerals: 100, gas: 100,
      prerequisites: ["forge"], producedBy: "forge" },
    p_ground_weapons_2: { id: "p_ground_weapons_2", name: "Ground Weapons +2", race: "protoss", type: "upgrade",
      buildTime: 154, minerals: 175, gas: 175,
      prerequisites: ["forge", "twilight_council", "p_ground_weapons_1"], producedBy: "forge" },
    p_ground_weapons_3: { id: "p_ground_weapons_3", name: "Ground Weapons +3", race: "protoss", type: "upgrade",
      buildTime: 180, minerals: 250, gas: 250,
      prerequisites: ["forge", "twilight_council", "p_ground_weapons_2"], producedBy: "forge" },
    p_ground_armor_1: { id: "p_ground_armor_1", name: "Ground Armor +1", race: "protoss", type: "upgrade",
      buildTime: 128, minerals: 100, gas: 100,
      prerequisites: ["forge"], producedBy: "forge" },
    p_shields_1: { id: "p_shields_1", name: "Shields +1", race: "protoss", type: "upgrade",
      buildTime: 144, minerals: 150, gas: 150,
      prerequisites: ["forge"], producedBy: "forge" },

    // ---- Zerg upgrades ----
    metabolic_boost: { id: "metabolic_boost", name: "Metabolic Boost", race: "zerg", type: "upgrade",
      buildTime: 79, minerals: 100, gas: 100,
      prerequisites: ["spawning_pool"], producedBy: "spawning_pool",
      note: "Zergling speed (+60%)" },
    adrenal_glands: { id: "adrenal_glands", name: "Adrenal Glands", race: "zerg", type: "upgrade",
      buildTime: 93, minerals: 200, gas: 200,
      prerequisites: ["spawning_pool", "hive"], producedBy: "spawning_pool",
      note: "Zergling attack speed" },
    centrifugal_hooks: { id: "centrifugal_hooks", name: "Centrifugal Hooks", race: "zerg", type: "upgrade",
      buildTime: 71, minerals: 100, gas: 100,
      prerequisites: ["baneling_nest", "lair"], producedBy: "baneling_nest",
      note: "Baneling speed + HP" },
    glial_reconstitution: { id: "glial_reconstitution", name: "Glial Reconstitution", race: "zerg", type: "upgrade",
      buildTime: 54, minerals: 100, gas: 100,
      prerequisites: ["roach_warren", "lair"], producedBy: "roach_warren",
      note: "Roach speed" },
    tunneling_claws: { id: "tunneling_claws", name: "Tunneling Claws", race: "zerg", type: "upgrade",
      buildTime: 79, minerals: 150, gas: 150,
      prerequisites: ["roach_warren", "lair"], producedBy: "roach_warren",
      note: "Roach burrowed movement + heal" },
    muscular_augments: { id: "muscular_augments", name: "Muscular Augments", race: "zerg", type: "upgrade",
      buildTime: 71, minerals: 100, gas: 100,
      prerequisites: ["hydralisk_den"], producedBy: "hydralisk_den",
      note: "Hydralisk speed" },
    grooved_spines: { id: "grooved_spines", name: "Grooved Spines", race: "zerg", type: "upgrade",
      buildTime: 71, minerals: 75, gas: 75,
      prerequisites: ["hydralisk_den"], producedBy: "hydralisk_den",
      note: "Hydralisk +1 range" },
    adaptive_talons: { id: "adaptive_talons", name: "Adaptive Talons", race: "zerg", type: "upgrade",
      buildTime: 57, minerals: 100, gas: 100,
      prerequisites: ["lurker_den"], producedBy: "lurker_den",
      note: "Lurker faster burrow" },
    seismic_spines: { id: "seismic_spines", name: "Seismic Spines", race: "zerg", type: "upgrade",
      buildTime: 79, minerals: 150, gas: 150,
      prerequisites: ["lurker_den", "hive"], producedBy: "lurker_den",
      note: "Lurker +2 range" },
    chitinous_plating: { id: "chitinous_plating", name: "Chitinous Plating", race: "zerg", type: "upgrade",
      buildTime: 79, minerals: 150, gas: 150,
      prerequisites: ["ultralisk_cavern"], producedBy: "ultralisk_cavern",
      note: "Ultralisk +2 armor" },
    anabolic_synthesis: { id: "anabolic_synthesis", name: "Anabolic Synthesis", race: "zerg", type: "upgrade",
      buildTime: 43, minerals: 150, gas: 150,
      prerequisites: ["ultralisk_cavern"], producedBy: "ultralisk_cavern",
      note: "Ultralisk speed off creep" },
    burrow: { id: "burrow", name: "Burrow", race: "zerg", type: "upgrade",
      buildTime: 71, minerals: 100, gas: 100,
      prerequisites: ["hatchery"], producedBy: "hatchery",
      note: "Researched at Hatch/Lair/Hive; allows units to burrow" },
    pneumatized_carapace: { id: "pneumatized_carapace", name: "Pneumatized Carapace", race: "zerg", type: "upgrade",
      buildTime: 60, minerals: 100, gas: 100,
      prerequisites: ["hatchery"], producedBy: "hatchery",
      note: "Overlord/Overseer speed" },
    // Pathogen Glands — REMOVED in patch 5.0.12 (Infestor base energy raised 50→75 instead)
    neural_parasite: { id: "neural_parasite", name: "Neural Parasite", race: "zerg", type: "upgrade",
      buildTime: 79, minerals: 150, gas: 150,
      prerequisites: ["infestation_pit"], producedBy: "infestation_pit",
      note: "Infestor mind-control" },
    microbial_shroud: { id: "microbial_shroud", name: "Microbial Shroud", race: "zerg", type: "upgrade",
      buildTime: 79, minerals: 150, gas: 150,
      prerequisites: ["infestation_pit"], producedBy: "infestation_pit",
      note: "Infestor anti-air shroud (research re-introduced in 5.0.15)" },
    z_melee_1: { id: "z_melee_1", name: "Melee Attacks +1", race: "zerg", type: "upgrade",
      buildTime: 114, minerals: 100, gas: 100,
      prerequisites: ["evolution_chamber"], producedBy: "evolution_chamber" },
    z_missile_1: { id: "z_missile_1", name: "Missile Attacks +1", race: "zerg", type: "upgrade",
      buildTime: 114, minerals: 100, gas: 100,
      prerequisites: ["evolution_chamber"], producedBy: "evolution_chamber" },
    z_carapace_1: { id: "z_carapace_1", name: "Ground Carapace +1", race: "zerg", type: "upgrade",
      buildTime: 114, minerals: 150, gas: 150,
      prerequisites: ["evolution_chamber"], producedBy: "evolution_chamber" },
  },
};
